### ISSUE TITLE
有计划支持ios和android吗？

### ISSUE THREAD

**Issue by disburden** [Fclash/Fclash#20]
我在linux和windows上都用了，挺好的，希望能一统天下

**Comment by Kingtous** [comment]
有这个想法，现在有一些api需要迁移到ffi。迁移完就有可能了

**Comment by disburden** [comment]
狂拽酷炫吊炸天

**Comment by Kingtous** [comment]
1.3.6已增加Android Beta安装包。目前不支持vpn方式设置代理。

https://github.com/Kingtous/Fclash/releases/tag/v1.3.6

**Comment by Kingtous** [comment]
1.3.11 新增vpn方式设置代理，支持SDK>29的Android系统。iOS支持已移入https://github.com/Fclash/Fclash/issues/22
