### ISSUE TITLE
请问以后会支持opensuse吗，我在ubuntu22.04上运行非常正常

### ISSUE THREAD

**Issue by majorzpley** [Fclash/Fclash#26]

**Comment by Kingtous** [comment]
deb包转换成rpm包安装试试？

**Comment by majorzpley** [comment]
我在opensuse leap15.5上用的snap版本的fclash已经可以成功运行了，但是关闭或者退出的时候程式并没有完全退出，进程没有杀死，不过已经可以代理了

**Comment by majorzpley** [comment]
另外suse应该只有gnome版本和xfce版本才能装上，kde版本会提示gtk错误

**Comment by Kingtous** [comment]
> 我在opensuse leap15.5上用的snap版本的fclash已经可以成功运行了，但是关闭或者退出的时候程式并没有完全退出，进程没有杀死，不过已经可以代理了

snap版本很久没更新了，估计有点问题

**Comment by Kingtous** [comment]
新增了rpm打包，可以试一下？

https://github.com/Kingtous/Fclash/releases

**Comment by majorzpley** [comment]
> 新增了rpm打包，可以试一下？
> 
> https://github.com/Kingtous/Fclash/releases

**Comment by majorzpley** [comment]
我下载了1.3.8的rpm包，我是opensuse的kde桌面，发现安装的时候老是会提示缺少动态库，但是我不懂这是什么库
![Screenshot_20230121_191054](https://user-images.githubusercontent.com/82143311/213864358-c37bbfd1-6ebe-4c09-9996-e36a28992247.png)

**Comment by majorzpley** [comment]
我安装上flutter之后前面那个依赖解决了，但是有出现了这个
![Screenshot_20230121_210511](https://user-images.githubusercontent.com/82143311/213868132-57dd119d-7868-45b9-8429-208ea62d3123.png)

**Comment by Kingtous** [comment]
> 我安装上flutter之后前面那个依赖解决了，但是有出现了这个
> ![Screenshot_20230121_210511](https://user-images.githubusercontent.com/82143311/213868132-57dd119d-7868-45b9-8429-208ea62d3123.png)
> 

用应该可以正常用吧。这些库是内部打包的依赖，不需要装flutter的。我写一下provides，这个是打包脚本的问题

**Comment by majorzpley** [comment]
> > 我安装上flutter之后前面那个依赖解决了，但是有出现了这个
> > ![Screenshot_20230121_210511](https://user-images.githubusercontent.com/82143311/213868132-57dd119d-7868-45b9-8429-208ea62d3123.png)
> 
> 用应该可以正常用吧。这些库是内部打包的依赖，不需要装flutter的。我写一下provides，这个是打包脚本的问题

忽略依赖安装的话启动不了

**Comment by Kingtous** [comment]
rpm包 1.3.10已修复
