### ISSUE TITLE
1.3.9 win版 无法显示应用

### ISSUE THREAD

**Issue by Aoereally** [Fclash/Fclash#33]
![image](https://user-images.githubusercontent.com/121400760/221102582-fde9c87c-185c-494f-88d7-975222bea213.png)

**Comment by depfish** [comment]
用管理员用户运行会有这个问题

**Comment by Kingtous** [comment]
不要使用管理员用户运行本程序

**Comment by Kingtous** [comment]
可以试试1.3.11
