### ISSUE TITLE
manjaro 最新版，打不开

### ISSUE THREAD

**Issue by luoyuanxiang** [Fclash/Fclash#40]
控制台启动报：
./fclash: error while loading shared libraries: libayatana-appindicator3.so.1: cannot open shared object file: No such file or directory

**Comment by Kingtous** [comment]
手动pacman装一下这个库

**Comment by iasukas** [comment]
> 手动pacman装一下这个库

我用fedora 38也是同样的报错，我安装了pacman，还是同样的报错

./fclash: error while loading shared libraries: libayatana-appindicator3.so.1: cannot open shared object file: No such file or directory

**Comment by Kingtous** [comment]
系统安装一下libaya这个库，下个版本我加上这个依赖



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月22日(周六) 晚上9:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Fclash/Fclash] manjaro 最新版，打不开 (Issue #40)




  
手动pacman装一下这个库
  
我用fedora 38也是同样的报错，我安装了pacman，还是同样的报错
 
./fclash: error while loading shared libraries: libayatana-appindicator3.so.1: cannot open shared object file: No such file or directory

**Comment by iasukas** [comment]
> 系统安装一下libaya这个库，下个版本我加上这个依赖
> [...](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年4月22日(周六) 晚上9:06 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [Fclash/Fclash] manjaro 最新版，打不开 (Issue #40) 手动pacman装一下这个库 我用fedora 38也是同样的报错，我安装了pacman，还是同样的报错 ./fclash: error while loading shared libraries: libayatana-appindicator3.so.1: cannot open shared object file: No such file or directory — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

这个库我看好像都是debian的 搞了半天 好像搞不太定 还是等下个版本吧 最近也要出差 也不急

**Comment by Kingtous** [comment]
> > 系统安装一下libaya这个库，下个版本我加上这个依赖
> > [...](#)
> > ---原始邮件--- 发件人: _**@**_._**> 发送时间: 2023年4月22日(周六) 晚上9:06 收件人: _**@**_.**_>; 抄送: _**@**_._**_**@**_.**_>; 主题: Re: [Fclash/Fclash] manjaro 最新版，打不开 (Issue #40) 手动pacman装一下这个库 我用fedora 38也是同样的报错，我安装了pacman，还是同样的报错 ./fclash: error while loading shared libraries: libayatana-appindicator3.so.1: cannot open shared object file: No such file or directory — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> 
> 这个库我看好像都是debian的 搞了半天 好像搞不太定 还是等下个版本吧 最近也要出差 也不急

Manjaro库里面有的， 我自己也是用Manjaro的：

https://software.manjaro.org/package/libayatana-appindicator

**Comment by xiaofami** [comment]
opensuse tumbleweed, 需要安装  libayatana-appindicator3-1
