### ISSUE TITLE
Mac os (intel) not support reality

### ISSUE THREAD

**Issue by conall1995** [Fclash/Fclash#49]
i try to use Fclash for reality its work fine on android  but cant import reality config

**Comment by Kingtous** [comment]
which version are u using? `1.4.0` or ?

**Comment by conall1995** [comment]
last version 1.4.0
![Screen Shot 2023-05-11 at 10 18 13 AM](https://github.com/Fclash/Fclash/assets/28934905/fc963b01-1fe0-4b1f-bbf3-b5ea2dcddc1b)
![Screen Shot 2023-05-11 at 10 18 52 AM](https://github.com/Fclash/Fclash/assets/28934905/fce2f6d5-6ecb-4df0-9b98-aaa54f6c3861)

**Comment by Kingtous** [comment]
please try 1.3.11，1.4.0 is not fully works now.

**Comment by conall1995** [comment]
Not work 

Considering that apparently in version 1.4 Clash core has been changed to Clash Meta and Clash does not support reality at all, in any case versions below 1.4 will not work.

**Comment by Kingtous** [comment]
You can try 1.3.11 first and check if it runs normally.
