### ISSUE TITLE
无意间发现了一个bug

### ISSUE THREAD

**Issue by AnyaParry** [Fclash/Fclash#5]

**Comment by Kingtous** [comment]
可以描述一下吗

**Comment by AnyaParry** [comment]
![image](https://user-images.githubusercontent.com/60728866/177712420-ac0e3296-7f15-4910-abda-368819e30858.png)
不好意思，有点操作不来，是这样的，再托盘图标右击，代理取消代理，然后列表就重复了

**Comment by Kingtous** [comment]
> 

我这边看一下。有兴趣提个PR吗？

**Comment by AnyaParry** [comment]
虽然但是，俺的技术栈跟flutter不一样，虽然会点kotlin，更多的还是vue ts。就不丢人现眼了。作者加油！

**Comment by AnyaParry** [comment]
是右击取消代理的时候，会对配置文件列表追加，只会追加一次。

**Comment by Kingtous** [comment]
试试1.3.6呢？

**Comment by Kingtous** [comment]
已修复
