### ISSUE TITLE
偶尔出现开启后很快闪退的情况

### ISSUE THREAD

**Issue by OSLike** [Fclash/Fclash#59]
本机为Ubuntu22.10，gnome43-X11，kernel 5.19.0-46-generic，x86_64，打开会卡一小段时间，如果这段时间对其进行操作会在不久后闪退。我不知道在哪里查看ERROR信息，我希望可以解决这个问题。

**Comment by Kingtous** [comment]
有log吗？deb安装还是snap？

**Comment by OSLike** [comment]
> 有log吗？deb安装还是snap？

新的版本貌似已經解決了，deb的
