### ISSUE TITLE
无法展开节点列表

### ISSUE THREAD

**Issue by gapplef** [Fclash/Fclash#65]
Fclash 1.4.3 snap  Ubuntu 22.04 Wayland
更新新版后在代理界面点击展开节点没反应

不清楚是否有帮助，不过终端启动时显示以下信息：
Gtk-Message: 11:42:13.704: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.
(fclash:6769): Gdk-CRITICAL **: 11:42:13.979: gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed

**Comment by Kingtous** [comment]
猜测是snap环境的问题，先用deb吧

**Comment by gapplef** [comment]
我回滚了之前版本。

不过有个新问题：没法自动设置系统代理，必须手动设置。之前就遇到过，中间重装过一次系统，问题没了，现在又出现了同样的问题。

**Comment by Kingtous** [comment]
1.4.3 build55 snap回滚了flutter 3.13 到 3.10.x，现在已经没问题了，可以试试

**Comment by gapplef** [comment]
问题解决了，谢谢！

**Comment by gapplef** [comment]
终端启动，对比之前版本少了这个提示：
(fclash:6769): Gdk-CRITICAL **: 11:42:13.979: gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed
似乎和这个bug有关 https://github.com/flutter/flutter/issues/130514
