### ISSUE TITLE
Bug: 1.4.3无法修改http代理端口

### ISSUE THREAD

**Issue by Renzishi** [Fclash/Fclash#67]
代理端口显示为0且无法修改，导致无法联网。

Pop!_OS 22.04 LTS
![截图 2023-09-10 15-50-51](https://github.com/Fclash/Fclash/assets/93137239/72fea08a-3d7c-4144-a681-610624d16c2e)

**Comment by liugangg** [comment]
+1

**Comment by Kingtous** [comment]
问题可以复现。如果影响使用可以先在yaml里面指定端口，或者用1.4.2-，和1.4.3区别不大。
应该是升级clash core，里面api改了导致的。

**Comment by Kingtous** [comment]
有能力帮忙找找，帮忙提个PR~

**Comment by liugangg** [comment]
> 问题可以复现。如果影响使用可以先在yaml里面指定端口，或者用1.4.2-，和1.4.3区别不大。 应该是升级clash core，里面api改了导致的。

感谢提醒，换成1.4.1可以了，

**Comment by Renzishi** [comment]
#72 
这个可能会有帮助

**Comment by Kingtous** [comment]
已合入，谢谢找到问题
