### ISSUE TITLE
ubuntu 22 配置切换不了，添加订阅连接取名为config下次打开则配置文件没有了，然后设置也显示不了了

### ISSUE THREAD

**Issue by luoyuanxiang** [Fclash/Fclash#9]
![image](https://user-images.githubusercontent.com/29119330/188139626-81825023-02c3-4be0-b72f-28031a4d7e31.png)
![image](https://user-images.githubusercontent.com/29119330/188139688-333385c0-575f-4c8f-8ab8-baf533b92c94.png)

**Comment by luoyuanxiang** [comment]
第一次打开的时候会崩溃

**Comment by Kingtous** [comment]
这些问题将在下一次重构解决，感谢反馈

**Comment by Kingtous** [comment]
> 第一次打开的时候会崩溃

建议取名不要用config默认名字，删除下`$HOME/.local/share/cn.kingtous.fclash/clash`文件夹载打开一下。

**Comment by fearry** [comment]
+1   
某些情况下添加订阅时没有正确生成配置文件导致无法切换配置文件
复制正确的文件到配置文件目录下可以正常用（使用其他已生成的clash配置文件）
使用第三方服务转换订阅链接至标准clash链接可以正常使用(不安全且显示结构可能发生改变)
Ubuntu22.04
Fclash 1.2.6-2

**Comment by Kingtous** [comment]
> +1   
> 某些情况下添加订阅时没有正确生成配置文件导致无法切换配置文件
> 复制正确的文件到配置文件目录下可以正常用（使用其他已生成的clash配置文件）
> 使用第三方服务转换订阅链接至标准clash链接可以正常使用(不安全且显示结构可能发生改变)
> Ubuntu22.04
> Fclash 1.2.6-2 ??
> ![截图 2022-11-02 21-44-47](https://user-images.githubusercontent.com/25784264/199505513-d06c8c4a-8f0b-4b85-9776-9d7f42d4911a.png)
> 

是最新版本吗

**Comment by fearry** [comment]
> 是最新版本吗
是的，我安装的是最新版1.3.4，不过系统报告的版本号和软件显示的不一致

**Comment by Kingtous** [comment]
> > 是最新版本吗
> 是的，我安装的是最新版1.3.4，不过系统报告的版本号和软件显示的不一致
> 

apt reinstall xxx.deb？

**Comment by Kingtous** [comment]
已经禁止了config命名，另外完成了所有Request API迁移，再试试1.3.6呢？

https://github.com/Kingtous/Fclash/releases/tag/v1.3.6
